# Name of your workflow
name: Build and Scan Docker Image

# Trigger the workflow on every push to the main branch
on:
  push:
    branches: [ "main" ]

# A job is a set of steps that execute on a virtual machine
jobs:
  build-and-scan:
    # The type of virtual machine to run the job on
    runs-on: ubuntu-latest

    # The steps that make up the job
    steps:
      # Step 1: Check out your code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Build the Docker image
      - name: Build the Docker image
        run: docker build -t my-flask-app:latest .

      # Step 3: NEW - Run Trivy vulnerability scanner
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-flask-app:latest'
          format: 'table'
          severity: 'CRITICAL,HIGH'